<?php


namespace Huixing\Bill;

use Illuminate\Support\Facades\Facade;

class App extends Facade
{
    public static function getFacadeAccessor()
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }

}
